# Generated by Django 3.1.7 on 2021-04-04 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('username', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Username')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='Email Address')),
                ('full_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Full Name')),
                ('dept_sec', models.CharField(blank=True, max_length=100, null=True, verbose_name='Department or Section')),
                ('designation', models.CharField(blank=True, max_length=100, null=True, verbose_name='Designation')),
                ('contact_no', models.CharField(blank=True, max_length=11, null=True, unique=True, verbose_name='Contact Number')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Date Joined..')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='Last Logged in')),
                ('profile_image', models.ImageField(blank=True, default='defaultuser.png', max_length=255, null=True, upload_to='')),
                ('active', models.BooleanField(default=True)),
                ('staff', models.BooleanField(default=False)),
                ('admin', models.BooleanField(default=False)),
                ('chairman', models.BooleanField(default=False)),
                ('vadmin', models.BooleanField(default=False)),
                ('vsubadmin', models.BooleanField(default=False)),
                ('accountant', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
