# Generated by Django 3.1.7 on 2021-03-16 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210316_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='contact_no',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True, verbose_name='Contact Number'),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='dept_sec',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Department or Section'),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='designation',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Designation'),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='email',
            field=models.EmailField(max_length=100, unique=True, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='full_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Full Name'),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Username'),
        ),
    ]
