# Generated by Django 3.2.4 on 2021-06-26 08:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vmsUser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startingkm', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Enter starting value...')),
                ('endingkm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Enter ending value...')),
                ('startingfuel', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Enter starting fuel...')),
                ('endingfuel', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Enter ending fuel...')),
                ('suppliedfuel', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Enter spent fuel...')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('requisition', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requisition', to='vmsUser.requisition')),
            ],
        ),
    ]
