# Generated by Django 4.0 on 2021-12-30 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vmsAdmin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicles',
            name='costperhr',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Cost per hour'),
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='costperkm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Cost per km'),
        ),
    ]
