# Generated by Django 3.1.7 on 2021-06-25 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vmsAdmin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drivers',
            name='drvr_vcl',
        ),
        migrations.AddField(
            model_name='drivers',
            name='drvr_type',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Driver Catagory'),
        ),
        migrations.AddField(
            model_name='drivers',
            name='vehicles',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vmsAdmin.vehicles'),
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='costperhr',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Cost per hour'),
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='costperkm',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, max_length=20, null=True, verbose_name='Cost per km'),
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='vcl_type',
            field=models.CharField(blank=True, choices=[('Ambulance', 'Ambulance'), ('Micro-Bus', 'Micro-Bus'), ('Pick-Up', 'Pick-Up'), ('AC-Minibus', 'AC-Minibus'), ('Non-AC Minibus', 'Non-AC Minibus'), ('Single Deck Bus', 'Single Deck Bus'), ('Double Deck Bus', 'Double Deck Bus')], max_length=200, null=True, verbose_name='Vehicle Category'),
        ),
    ]
