# Generated by Django 3.2.4 on 2021-06-26 08:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Requisition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aplctn_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Requisition Date')),
                ('jour_purpose', models.CharField(blank=True, choices=[('Individual', 'Individual'), ('Official', 'Official')], max_length=100, null=True, verbose_name='Journey Purpose')),
                ('jour_date', models.DateField(blank=True, null=True, verbose_name='Journey Date')),
                ('vcl_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='Vehicle Type')),
                ('destination', models.CharField(blank=True, max_length=200, null=True, verbose_name='Destination')),
                ('departr_time', models.TimeField(blank=True, null=True, verbose_name='Departure Time')),
                ('rtrn_time', models.TimeField(blank=True, null=True, verbose_name='Return Time')),
                ('jour_details', models.CharField(blank=True, max_length=400, null=True, verbose_name='Journey Details')),
                ('is_requisited', models.BooleanField(default=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
