# Generated by Django 3.1.6 on 2021-04-04 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Requisitionforms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aplctn_date', models.DateField(blank=True, null=True, verbose_name='Date')),
                ('user_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='User Name')),
                ('designation', models.CharField(blank=True, max_length=100, verbose_name='Designation')),
                ('department', models.CharField(blank=True, max_length=100, null=True, verbose_name='Department')),
                ('jour_purpose', models.CharField(blank=True, max_length=100, null=True, verbose_name='Journey Purpose')),
                ('jour_date', models.DateField(blank=True, null=True, verbose_name='Journey Date')),
                ('vcl_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='Vehicle Type')),
                ('destination', models.CharField(blank=True, max_length=200, null=True, verbose_name='Destination')),
                ('deprtr_time', models.TimeField(blank=True, null=True, verbose_name='Departure Time')),
                ('rtrn_time', models.TimeField(blank=True, null=True, verbose_name='Return Time')),
                ('jour_details', models.CharField(blank=True, max_length=400, null=True, verbose_name='Journey Details')),
            ],
        ),
    ]
