# Generated by Django 3.1.6 on 2021-04-04 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vmsuser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisitionforms',
            name='aplctn_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='requisitionforms',
            name='jour_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Journey Date'),
        ),
    ]
